### ISSUE TITLE
In the selector option, do i have to provide the entire svg element, or can i access only one path element inside the svg

### ISSUE THREAD

**Issue by abhijeetramgir** [ConnorAtherton/walkway#43]
In the selector option, do I have to provide the entire svg element, or can i target only one path element inside the svg?
Thanks

**Comment by carnye** [comment]
Currently, Walkway only supports selecting by SVG elements

**Comment by ConnorAtherton** [comment]
@abhijeetramgir Yeah, what @carnye said. It seems like we need to make a choice between what you are describing and the behaviour we currently have. Either we only accept selectors that match exact what individual elements, or we support a parent selector and select every child that matches nodes we support. I opted for the latter because that seemed like a more common, approachable solution to the problem of animation SVG's, especially ones that have a lot of children. 

Closing. Please reach out if you need more help with this.
