### ISSUE TITLE
add option for complete on visibilitychange

### ISSUE THREAD

**Issue by DanielRuf** [ConnorAtherton/walkway#46]
The next tagged release would break many existing projects as the animations would not keep running but immediately complete on visibilitychange.

This should not be the case by default and just be enabled with another parameter when creating a Walkway instance.

It could also make sense to provide an argument (function) to override the behavior when the visibility of the tab changes. Should the animation reset or complete? Or should the visibilitychange in the current master be removed and developers have to add the desired behavior to their own code?

Because like you said in another issue, Walkway should not depend on any viewport things and just be used for the actual animation.

**Comment by ConnorAtherton** [comment]
> would not keep running but immediately complete on visibilitychange

It won't break anything, for two reasons. First, it is actually already in the current release https://github.com/ConnorAtherton/walkway/blob/v0.0.7/src/walkway.js#L114. Second, that was explicitly added because the alternative was buggy. It doesn't matter if the animation keeps going, because having that event fire means it will not be seen anyway (due to being in another tab, or something). 

> This should not be the case by default

I see your point. It initially wasn't but we had issues where people preferred the alternative behaviour, for things to work well by default, instead of people using this and ending up with half-drawn elements on the page and not knowing why. 

>  like you said in another issue, Walkway should not depend on any viewport things

Apologies for my mis-quote. I was trying to refer to the example you gave in your examples, which talked about bringing elements in from outside the viewport at different times, in which case I said the app should deal with that and Walkway focuses on just animating the elements.

**Comment by DanielRuf** [comment]
Ok. But why not add an option to disable the complete call on visibilitychange events? Or is this not a good idea to overwrite this behavior?

At least I just got 0.0.6 with npm install, no 0.0.7 release.
